src/pages/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from .views import ContactFormView, HomePage, LegalPage, PopularPage

app_name = "pages"
urlpatterns: list[URLPattern] = [
    path("legal/<slug:category>", LegalPage.as_view(), name="legal"),
    path("contact", ContactFormView.as_view(), name="contact"),
    path("popular", PopularPage.as_view(), name="popular"),
    path("", HomePage.as_view(), name="home"),
]

src/templates/pages/_contact_form.html
{% load i18n start fragments widget_tweaks %}
<form>
  {% csrf_token %}
  {% url 'pages:contact' as target_hx_url %}
  <div class="flex flex-col gap-4 justify-evenly">
    {% sel form.category idx='dwnr' %}
    {% hput form.email kls='fx' validate=target_hx_url %}
    {% hput form.message kls="fx" %}
  </div>
  <div class="mt-8">
    <button class="w-full btn" data-btn="primary" hx-post="{{target_hx_url}}" hx-target='#contact-form-area'>
      Let's Talk
    </button>
  </div>
</form>

src/templates/pages/_contact_form_area.html
<div id="contact-form-area">{% include './_contact_form.html' %}</div>

src/templates/pages/_contact_success.html
{% load fragments %}
<div class="px-6 sm:px-6 lg:px-8">
  {% icon name='envelope' css='w-6 h-6 fill-grayed stroke-white' parent_tag='div' parent_class='flex justify-center py-2' %}
  <div class="mx-auto max-w-2xl text-center">
    <h4 class="text-2xl font-bold tracking-tight sm:text-4xl">Thank you!</h4>
    <p class="mt-2 text-lg leading-8 text-grayed-muted">This partial HTML fragment is a response but without refreshing the page.</p>
  </div>
</div>

src/templates/pages/_feature.html
{% load start fragments %}
<section class="p-16 rounded-md shadow-lg dark:shadow-md hover:shadow-md dark:hover:shadow-lg dark:shadow-purple-800 hover:shadow-sky-200 hover:dark:shadow-purple-900">
  <div class="mx-auto sm:max-w-2xl sm:text-center">
    <p class="font-semibold dark:text-pink-400 text-base/7 text-sky-500">{{feature.caption}}</p>
    <h2 class="pt-2 text-3xl font-bold tracking-tight sm:text-4xl text-dawn dark:text-dusk">{{feature.headline}}</h2>
    <div class="mx-auto sm:max-w-md dark:text-grayed-muted">
      <p class="mt-6 dark:text-gray-300 feature text-lg/8 text-grayed">{{feature.description|md}}</p>
    </div>
    {% if feature.links %}
      <ul role="list" class="flex flex-col gap-2 pt-8">
        {% for link in feature.links %}
          <a href="{{link.url}}" target="_blank" class="focus:outline-none group">
            <li class="inline-flex items-center py-2 px-4 text-xs font-light text-gray-600 bg-gray-300 rounded-full sm:text-base dark:text-pink-100 dark:bg-gray-800 hover:text-green-100 dark:hover:bg-pink-700 group-focus:dark:bg-pink-700/40 group-focus:bg-dawn/40 hover:bg-dawn">
              {% icon name=link.icon_name css="h-4 w-4 sm:h-6 sm:w-6" post_text=link.label post_class="ml-3"  %}
            </li>
          </a>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
</section>

src/templates/pages/_repo.html
{% load start fragments %}
<section class="m-4 shadow sm:rounded-md hover:shadow-lg group/main dark:shadow-purple-800">
  <div class="py-4 px-4 sm:py-12 sm:px-10">
    <a href="https://github.com/{{repo.owner_name}}/{{repo.repo_name}}" class="focus:outline-none group/sub" target="blank">
      <div class="overflow-hidden relative group-hover/main:backdrop-blur-sm group-focus/sub:backdrop-blur-sm">
        <img width=560 height=280 class="mx-auto rounded-md group-hover/main:opacity-30 group-hover/main:grayscale group-focus/sub:opacity-30 group-focus/sub:grayscale" src="{{repo.og_image}}" {% if forloop.counter > 6 %}loading="lazy"{% endif %} alt="An open graph image from Github of {{repo.repo_name}}">
        <div class="flex absolute right-0 left-0 top-1/2 items-end mx-4 opacity-0 group-hover/main:opacity-100 group-focus/sub:opacity-100" aria-hidden="true">
          <div class="py-2 px-4 w-full text-sm font-medium text-center text-gray-200 bg-opacity-75 rounded-md bg-dawn-darker dark:bg-fuchsia-400/90">View on Github</div>
        </div>
      </div>
    </a>
    <div class="flex justify-between mt-2 text-xs text-gray-500 sm:mt-3 sm:text-base">
      <span class="flex items-center" title="Repository created on: {{repo.created_at}}">
        {% icon name='calendar' css="mr-1 h-4 w-4" post_text=repo.created_at|date:"Y" %}
      </span>
      <span class="flex items-center" title="Repository updated on: {{repo.updated_at}}, as checked on {{repo.timestamp}}">
        {% icon name='wrench_screwdriver' css="mr-1 h-4 w-4" post_text=repo.updated_at|date:"Y" %}
      </span>
      <a href="https://github.com/{{repo.owner_name}}" title="{{repo.description}}" class="hover:underline focus:underline focus:outline-none dark:focus:decoration-dusk dark:hover:decoration-dusk dark:hover:focus:decoration-dusk hover:underline-offset-4 hover:decoration-dawn focus:underline-offset-4 focus:decoration-dawn">
        {% icon parent_class="flex items-center" name='user_circle' css="mr-1 h-4 w-4" post_text=repo.owner_name %}
      </a>
    </div>
  </div>
</section>

src/templates/pages/contact.html
{% extends "base.html" %}
{% load i18n start %}
{% block title %}{% trans "Contact mv3" %}{% endblock title %}

{% block content %}
  {% include '_msg.html' with messages=form.non_field_errors %}
  {% trans "Contact Me" as heading %}
  {% trans "Feel free to leave a note!" as caption %}
  {% include 'text/header_fragment.html' with heading=heading caption=caption cta="pages/_contact_form_area.html"%}
{% endblock content %}

src/templates/pages/home.html
{% extends 'base.html' %}
{% load start fragments %}
{% block content %}
  <div class="py-24 px-6 mx-auto max-w-2xl sm:py-6 lg:px-8">
    <div class="hidden sm:flex sm:justify-center sm:mb-8">
      <div class="relative py-1 px-3 rounded-full ring-1 text-sm/6 ring-gray-900/10 dark:ring-gray-300/10 dark:hover:ring-gray-300/20 hover:ring-gray-900/20">
        Choose this... or one of many popular boilerplates <a href="{% url 'pages:popular' %}" class="italic dark:text-purple-300 hover:font-bold focus:font-bold focus:outline-none text-dawn"><span class="absolute inset-0" aria-hidden="true"></span><span aria-hidden="true">&rarr;</span></a>
      </div>
    </div>
    <div class="text-center">
      <h1 class="text-5xl font-bold tracking-tight sm:text-6xl"><span class="text-grayed dark:text-grayed-lighter">start</span><span class="text-grayed-muted dark:text-grayed">-</span><span class="text-dawn dark:text-dusk">django</span></h1>
      <p class="mx-auto mt-6 max-w-xl font-thin text-lg/8 text-grayed dark:text-grayed-lighter">
        css: <a target="_blank" href="https://tailwindcss.com" class="font-semibold underline focus:outline-none underline-offset-4 decoration-dusk hover:decoration-4 focus:decoration-4">TailwindCSS</a>
        <br>reactive: <a target="_blank" href="https://htmx.org" class="font-semibold underline focus:outline-none underline-offset-4 decoration-pink-600 hover:decoration-4 focus:decoration-4">htmx</a>
        <br>scripted: <a target="_blank" href="https://hyperscript.org" class="font-semibold underline focus:outline-none underline-offset-4 decoration-cyan-600 hover:decoration-4 focus:decoration-4">hyperscript</a>
        <br>deployable: <a target="_blank" href="https://fly.io" class="font-semibold underline focus:outline-none underline-offset-4 decoration-sky-600 hover:decoration-4 focus:decoration-4">fly.io</a>
      </p>
      <div class="flex gap-x-4 justify-center items-center mt-10">
        {% icon name="github" prefix="bootstrap" css="h-6 w-6" aria_hidden="true" post_text="Code" parent_tag="a" parent_type="button" parent_href="https://github.com/justmars/start-django" parent_class="inline-flex gap-x-2 items-center py-2.5 px-3.5 text-sm font-semibold text-white rounded-md shadow-sm focus:rounded-md focus:ring-2 focus:ring-offset-4 focus:ring-offset-green-300 focus:outline-none bg-zinc-900 dark:bg-grayed-darker dark:hover:bg-purple-600 dark:focus:ring-dusk dark:focus:ring-offset-purple-300 hover:bg-dawn focus:ring-dawn" %}
        {% icon name="markdown" prefix="bootstrap" css="h-6 w-6" aria_hidden="true" post_text="Docs" parent_tag="a" parent_type="button" parent_href="https://mv3.dev/start-django" parent_class="inline-flex gap-x-2 items-center py-2.5 px-3.5 text-sm font-semibold text-white rounded-md shadow-sm focus:rounded-md focus:ring-2 focus:ring-offset-4 focus:ring-offset-green-300 focus:outline-none bg-zinc-900 dark:bg-grayed-darker dark:hover:bg-purple-600 dark:focus:ring-dusk dark:focus:ring-offset-purple-300 hover:bg-dawn focus:ring-dawn" %}
      </div>
    </div>
  </div>
  <ul role="list" class="px-6 mx-auto max-w-7xl lg:px-8">
    {% for feature in features %}
      <li class="py-2 sm:py-12 sm:px-6 lg:px-8">
        {% include './_feature.html' %}
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

src/templates/pages/legal.html
{% extends 'base.html' %}
{% block content %}
  <div class="mx-auto max-w-7xl sm:px-6 lg:px-8">
    <div class="flex flex-col">
      <header class="flex gap-2">
        {% include 'text/header_fragment.html' with heading=agreement.title caption=agreement.created|date %}
      </header>
      <div class="flex mx-auto">
        <div class="p-8 max-w-2xl">
          {% for clause in clauses %}
            <section class="my-10">
              <details class="p-6 rounded-lg open:bg-white open:ring-1 open:ring-black/5 open:shadow-lg dark:open:bg-slate-900 dark:open:ring-white/10" open>
                <summary class="text-sm font-semibold leading-6 select-none dark:text-white text-slate-900">
                  {% lorem 3 w %}
                </summary>
                <div class="mt-3 text-sm leading-6 prose text-slate-600 dark:text-slate-400">
                  {% lorem 1 p %}
                </div>
              </details>
            </section>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

src/templates/pages/popular.html
{% extends 'base.html' %}
{% load i18n fragments %}
{% block extra_meta %}
  {% og_title text="Community-Driven Starters " request=request %}
  {% og_desc text="A list of starter projects" %}
{% endblock extra_meta %}

{% block content %}
  {% trans "Popular Boilerplates" as heading %}
  {% trans "If this boilerplate isn't your cup of tea, there are many other options available." as caption %}
  {% include 'text/header_fragment.html' with heading=heading caption=caption %}
  <div class="mx-auto max-w-2xl">
    <ul role="list" class="space-y-3">
      {% for starter in starters %}
        <li class="overflow-hidden">
          {% include './_repo.html' with repo=starter %}
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock content %}