src/pages/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from .views import ContactFormView, HomePage, LegalPage, PopularPage

app_name = "pages"
urlpatterns: list[URLPattern] = [
    path("legal/<slug:category>", LegalPage.as_view(), name="legal"),
    path("contact", ContactFormView.as_view(), name="contact"),
    path("popular", PopularPage.as_view(), name="popular"),
    path("", HomePage.as_view(), name="home"),
]

src/profiles/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from .views import (
    hx_del_user_post,
    hx_img_post,
    hx_personal_data_post,
    public_profile,
    tab_account_data,
    tab_personal_data,
)

app_name = "profiles"
urlpatterns: list[URLPattern] = [
    path(
        route="u/<slug:username>",
        view=public_profile,
        name="detail",
    ),
    path(
        route="settings/personal_data/post",
        view=hx_personal_data_post,
        name="hx_personal_data_post",
    ),
    path(
        route="settings/image/post",
        view=hx_img_post,
        name="hx_img_post",
    ),
    path(
        route="settings/security/user/delete/post",
        view=hx_del_user_post,
        name="hx_del_user_post",
    ),
    path(
        route="settings/account_data",
        view=tab_account_data,
        name="settings_account_data",
    ),
    path(
        route="",
        view=tab_personal_data,
        name="settings",
    ),
]

src/templates/_msg.html
{% load fragments %}
<div id="alerts-hq" {% if messages %}hx-swap-oob="true"{% endif %} role="alert" class="flex fixed inset-0 z-10 items-end py-6 px-4 pointer-events-none sm:items-start sm:p-6">
  <div class="flex flex-col items-center space-y-4 w-full sm:items-end">
    {% for message in messages %}
      <div id="msg-{{forloop.counter}}" _="on load show me"
        data-level="{{message.level_tag|lower}}"
        class="{{message.tags}} overflow-hidden z-20 w-full max-w-sm rounded-lg shadow-lg pointer-events-auto
          data-[level=success]:bg-green-300 dark:data-[level=success]:bg-fuchsia-600
          data-[level=info]:bg-sky-300 dark:data-[level=info]:bg-blue-800
          data-[level=warning]:bg-yellow-500-300 dark:data-[level=warning]:bg-orange-400 dark:data-[level=warning]:text-gray-700
          data-[level=error]:bg-red-300 dark:data-[level=error]:bg-rose-500"
        >
        <div class="flex items-center p-4">
          <div class="flex flex-1 justify-between w-0">
            <p class="flex-1 w-0 text-sm font-medium text-grayed dark:text-grayed-lighter">{{message}}</p>
          </div>
          <div class="flex flex-shrink-0 ml-4">
            <button _="on click remove #msg-{{forloop.counter}} end" id="msg-close-{{forloop.counter}}" type="button" class="inline-flex rounded-md">
              {% icon name='x_mark_mini' css="h-5 w-5 " pre_text="Close" pre_class="sr-only" aria_hidden="true" %}
            </button>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>

src/templates/_nav.html
{% load static fragments start %}
<div hidden id="mobile-menu" role="dialog" aria-modal="true">{# mobile menu: hidden on large view ports #}
  <div class="overflow-y-auto fixed inset-0 z-10 py-6 px-8 lg:hidden bg-grayed-lighter dark:bg-grayed">
    <div class="flex justify-between items-center">
      <button _="on click toggle @hidden on #mobile-menu end" type="button" class="p-2.5 -m-2.5 text-gray-700 rounded-md dark:text-grayed-lighter">
        {% icon name='x_mark_mini' pre_text="Close menu" aria_hidden="true" pre_class="sr-only" %}
      </button>
    </div>
    <div class="flex flex-col py-6 space-y-2">
      {% nava 'pages:home' 'Home' css='burger' request=request %}
      {% nava 'pages:popular' 'Popular' css='burger' request=request %}
      {% nava 'pages:contact' 'Contact' css='burger' request=request %}
    </div>
  </div>
</div>
<div aria-hidden="true" class="overflow-hidden absolute inset-x-0 transform-gpu top-[-10rem] -z-10 blur-3xl sm:top-[-20rem]">{# generic gradient #}
  <svg class="relative left-[calc(50%-11rem)] -z-10 h-[21.1875rem] max-w-none -translate-x-1/2 rotate-[30deg] sm:left-[calc(50%-30rem)] sm:h-[42.375rem]" viewBox="0 0 1155 678">
    <path fill="url(#45de2b6b-92d5-4d68-a6a0-9b9b2abad533)" fill-opacity=".3" d="M317.219 518.975L203.852 678 0 438.341l317.219 80.634 204.172-286.402c1.307 132.337 45.083 346.658 209.733 145.248C936.936 126.058 882.053-94.234 1031.02 41.331c119.18 108.451 130.68 295.337 121.53 375.223L855 299l21.173 362.054-558.954-142.079z" />
    <defs>
      <linearGradient id="45de2b6b-92d5-4d68-a6a0-9b9b2abad533" x1="1155.49" x2="-78.208" y1=".177" y2="474.645" gradientUnits="userSpaceOnUse">
        <stop stop-color="#9089FC" />
        <stop offset="1" stop-color="#FF80B5" />
      </linearGradient>
    </defs>
  </svg>
</div>
<nav class="flex justify-between items-center" aria-label="main-nav">{# if more than <nav> element in a document, provide a label #}
  <div class="hidden ml-3 lg:flex lg:flex-1">
    {% icon name='forward' css='icon' parent_tag="a" parent_class="desktop" parent_href="/" %}{# home icon #}
  </div>
  <div class="flex ml-4 lg:hidden">
    <button type="button" class="rounded-md" _="on click toggle @hidden on #mobile-menu end">
      {% icon name='bars_3' css='icon' pre_text="Open main menu" pre_class="sr-only" aria_hidden="true" %}
    </button>{# lg-view: burger ('bars_3') hidden; else burger replaces home icon, visually #}
  </div>
  <div class="hidden lg:flex lg:gap-x-12">
    {% nava 'pages:popular' 'Popular' css="desktop" request=request %}
    {% nava 'pages:contact' 'Contact' css="desktop" request=request %}
  </div>{# desktop links; hidden on small view ports. visible mobile links on burger icon click #}
  <div class="flex gap-2 items-center mr-4 lg:flex-1 lg:justify-end">{# right edge of desktop / mobile nav #}
    {% themer icon1_name="sun" icon1_css="dark:hidden icon" icon2_name="moon" icon2_css="hidden dark:block icon" btn_kls="desktop flex justify-center items-center rounded-md transition" %}
    {% static "img/smiler.png" as default_img %}
    {% if not request.user.is_authenticated %}
      {% nava 'account_login' 'Login' css='desktop' request=request %}
    {% else %} {# see django-fragments' _nav.html #}
      <div id="auth-menu" class="relative ml-3" _="on load js doMenu('auth-menu') end end">
        <button class="desktop">
          <span class="sr-only">Open user menu</span>
          {% if user.profile.image_url != default_img %}<img class="w-6 h-6 rounded-full sm:w-8 sm:h-8" src="{{user.profile.image_url|variant:'avatar'}}" alt="{{user.profile.fullname}}">
          {% else %}{% icon name='user' css='icon' %}{% endif %}
        </button>
        <ul hidden role="menu" class="absolute right-0 z-10 py-1 mt-2 w-48 rounded-md ring-1 ring-black ring-opacity-5 shadow-lg transition duration-200 ease-out transform origin-top-right scale-95 cursor-pointer focus:outline-none bg-slate-100 dark:bg-grayed-darker">
          <li class="block py-2 px-4 text-sm text-grayed-darker data-[ok=true]:text-white data-[ok=true]:bg-dawn dark:text-grayed-lighter dark:data-[ok=true]:bg-dusk">
            <a href="{% url 'profiles:settings' %}" role="menuitem" tabindex="-1">Private Settings</a>
          </li>
          <li class="block py-2 px-4 text-sm text-grayed-darker data-[ok=true]:text-white data-[ok=true]:bg-dawn dark:text-grayed-lighter dark:data-[ok=true]:bg-dusk">
            <a href="{% url 'profiles:detail' user.username %}" role="menuitem" tabindex="-1">Public Profile</a>
          </li>
          <li class="block py-2 px-4 text-sm text-grayed-darker data-[ok=true]:text-white data-[ok=true]:bg-dawn dark:text-grayed-lighter dark:data-[ok=true]:bg-dusk">
            <a href="{% url 'account_logout' %}" role="menuitem" tabindex="-1">Logout</a>
          </li>
        </ul>
      </div>
    {% endif %}
  </div>
</nav>

src/templates/base.html
<!DOCTYPE html>
{% load static compress start fragments %}
{% spaceless %}
  {% compress js %}{# utils via django-fragments #}
    <script src="{% static 'doTheme.js' %}"></script>
    <script src="{% static 'doDropCommon.js' %}"></script>
    <script src="{% static 'doDropSelect.js' %}"></script>
    <script src="{% static 'doDropMenu.js' %}"></script>
  {% endcompress js %}
  <script>themeHTML()</script>
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1">
      {# SEO: Add <meta name="robots" content="noindex"> when not yet ready for public indexing in search engines  #}
      <link rel="shortcut icon" type="image/png" href="{% static 'img/favicons/favicon.ico' %}"/>
      <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicons/apple-touch-icon.png' %}">
      <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicons/favicon-32x32.png' %}">
      <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicons/favicon-16x16.png' %}">
      <link rel="manifest" href="{% static 'img/favicons/site.webmanifest' %}">{# List of icons #}
      {% block extra_meta %}{# seo #}
        {% og_desc "site simple grug boring: tailwind django htmx, start change here" %}
        <meta name="author" content="https://mv3.dev" />
      {% endblock extra_meta %}
      {% compress css %}
        <link rel="stylesheet" href="{% static 'css/output.css' %}">
      {% endcompress %}
    </head>
    <body {% htmx_csrf %} class="flex flex-col min-h-screen bg-stone-200 text-grayed selection:text-white selection:bg-dawn dark:bg-slate-900 dark:text-grayed-lighter dark:selection:text-dusk-darker dark:selection:bg-fuchsia-300">
      <header class="container py-4 mx-auto sm:py-8">
        {% include './_nav.html' %}
        {% include './_msg.html' %}
      </header>
      <main class="container flex-1 mx-auto">
        {% block content %}
        {% endblock content %}
      </main>
      <footer class="container my-4 mx-auto sm:py-4 bg-stone-200 dark:bg-slate-900">
        <div class="px-10">
          <ul role="list" class="flex justify-between space-x-10 sm:justify-end">
            <li><a href="{% url 'pages:legal' 'terms' %}" class="hover:underline focus:underline focus:outline-none text-xs/6 text-grayed-muted dark:text-grayed dark:focus:decoration-dusk dark:hover:decoration-dusk dark:hover:focus:decoration-dusk hover:underline-offset-4 hover:decoration-dawn focus:underline-offset-4 focus:decoration-dawn">Terms</a></li>
            <li><a href="{% url 'pages:legal' 'privacy' %}" class="hover:underline focus:underline focus:outline-none text-xs/6 text-grayed-muted dark:text-grayed dark:focus:decoration-dusk dark:hover:decoration-dusk dark:hover:focus:decoration-dusk hover:underline-offset-4 hover:decoration-dawn focus:underline-offset-4 focus:decoration-dawn">Privacy</a></li>
          </ul>
        </div>
      </footer>
      {% compress js %}
        <script src="{% static 'js/htmx.min.js' %}"></script> {# 1.9.2 #}
        <script src="{% static 'js/hyperscript.min.js' %}"></script> {# 0.9.8 #}
      {% endcompress js %}{% block extra_js %}{% endblock extra_js %}
    </body>
  </html>
{% endspaceless %}