src/pages/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from .views import ContactFormView, HomePage, LegalPage, PopularPage

app_name = "pages"
urlpatterns: list[URLPattern] = [
    path("legal/<slug:category>", LegalPage.as_view(), name="legal"),
    path("contact", ContactFormView.as_view(), name="contact"),
    path("popular", PopularPage.as_view(), name="popular"),
    path("", HomePage.as_view(), name="home"),
]

src/profiles/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from .views import (
    hx_del_user_post,
    hx_img_post,
    hx_personal_data_post,
    public_profile,
    tab_account_data,
    tab_personal_data,
)

app_name = "profiles"
urlpatterns: list[URLPattern] = [
    path(
        route="u/<slug:username>",
        view=public_profile,
        name="detail",
    ),
    path(
        route="settings/personal_data/post",
        view=hx_personal_data_post,
        name="hx_personal_data_post",
    ),
    path(
        route="settings/image/post",
        view=hx_img_post,
        name="hx_img_post",
    ),
    path(
        route="settings/security/user/delete/post",
        view=hx_del_user_post,
        name="hx_del_user_post",
    ),
    path(
        route="settings/account_data",
        view=tab_account_data,
        name="settings_account_data",
    ),
    path(
        route="",
        view=tab_personal_data,
        name="settings",
    ),
]

src/profiles/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import PermissionDenied
from django.db import models
from django.shortcuts import get_object_or_404
from django.templatetags.static import static
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django_extensions.db.models import TimeStampedModel

from .utils import select_storage, set_base_img_url


class User(AbstractUser):
    def get_absolute_url(self):
        return reverse("profiles:detail", kwargs={"username": self.username})

    def get_social_url(self) -> str | None:
        socials = self.socialaccount_set  # type: ignore ; see django-allauth
        if socials.count():  # type: ignore ; see django-allauth
            if url := socials.first().get_avatar_url():
                return set_base_img_url(url)
        return None


class Profile(TimeStampedModel):
    """Creates some common properties:

    @property | description
    --:|:--
    `image_url` | The saved image related to the profile; if a `social_url` exists on signup, this is automatically used to create the `image_url`.
    `im_key` | Prevent duplicate names saved on file storage by establishing a convention for storing image files on each Profile

    """  # noqa: E501

    SuffixChoices = [
        ("Jr.", "Jr."),
        ("Sr.", "Sr."),
        ("III", "III"),
        ("IV", "IV"),
        ("V", "V"),
        ("VI", "VI"),
    ]
    GenderChoices = [("Male", "Male"), ("Female", "Female")]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    image = models.ImageField(storage=select_storage, blank=True, null=True)
    first_name = models.CharField(max_length=250, blank=True, null=True)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=250, blank=True, null=True)
    suffix = models.CharField(
        max_length=3, choices=SuffixChoices, blank=True, null=True
    )
    gender = models.CharField(
        max_length=7, choices=GenderChoices, blank=True, null=True
    )
    date_of_birth = models.DateField(_("Date of Birth"), blank=True, null=True)
    full_name = models.CharField(max_length=250)

    class Meta:
        db_table = "profiles"
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"

    def __str__(self):
        if self.user.first_name != "" and self.user.last_name != "":
            fields = (self.first_name, self.last_name, self.suffix)
            return " ".join(f for f in fields if f)
        return str(self.user.username)

    def save(self, *args, **kwargs):
        self.full_name = str(self)
        super().save()  # Call the real save() method

    @classmethod
    def get_for_user(cls, profile_id: int, user: User):
        """Simple permission checking"""
        profile = get_object_or_404(cls, id=profile_id)
        if profile.user != user:
            raise PermissionDenied()
        return profile

    @cached_property
    def im_key(self):
        """Identifying key for image to store."""
        return f"profiles/{self.user.username}"

    @property
    def image_url(self) -> str:
        """URL to stored image object of user profile (or default)."""
        if self.image:
            if self.image.name.startswith("https://"):
                return self.image.name
            elif self.image.storage.exists(self.image.name):
                return self.image.storage.url(self.image.name)
        return static("img/smiler.png")

src/templates/profiles/tabs/tab_account/_delete_profile_button.html
{% load fragments %}
<a type="button" class="btn" data-btn="danger" href="#del-user">Delete</a>
<section id="del-user" class="relative invisible z-10 opacity-0 transition-all duration-300 group target:visible target:opacity-100" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="overflow-y-auto fixed inset-0 z-10">
    <div class="flex justify-center items-end p-4 min-h-full text-center sm:items-center sm:p-0">
      <a href="#" class="block fixed inset-0 bg-opacity-75 transition-opacity cursor-default bg-black/50"><span class="sr-only">Close Modal</span></a>
      <div class="overflow-hidden relative text-left bg-white rounded-lg shadow-xl opacity-0 transition-all duration-300 transform scale-90 sm:my-8 sm:w-full sm:max-w-lg group-target:scale-100 group-target:opacity-100 dark:bg-grayed">
        {% include 'text/header_modal.html' with heading='Confirm Deletion' caption="Are you sure you want to deactivate your account? All of your data will be permanently removed. This action cannot be undone." icon_name='exclamation_triangle' icon_css="h-6 w-6 text-red-600 dark:text-red-100" background_icon_css="bg-red-100 dark:bg-red-600" %}
        <div class="gap-2 py-3 px-4 bg-gray-50 sm:flex sm:flex-row-reverse sm:px-6 dark:bg-gray-600">
          <button class="btn" data-btn="danger" hx-post='profiles:hx_del_user_post' hx-target="body">Delete</button>
          <a type="button" class="btn" href="#">Cancel</a>
        </div>
      </div>
    </div>
  </div>
</section>

src/templates/profiles/tabs/tab_account/_edit_image_form.html
<form id="img-form" action="{% url 'profiles:hx_img_post' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <label class="relative py-2 px-3.5 text-sm font-semibold text-white rounded-md shadow-sm cursor-pointer bg-grayed hover:bg-grayed-muted focus-visible:outline-grayed focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2">
    <span>Change</span>
    <input _="on change submit() with closest <form/> end" id="id_image" name="id_image" type="file" class="absolute top-0 left-0 w-full h-full opacity-0 cursor-pointer" />
  </label>
  <button hidden></button>
</form>