src/pages/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from .views import ContactFormView, HomePage, LegalPage, PopularPage

app_name = "pages"
urlpatterns: list[URLPattern] = [
    path("legal/<slug:category>", LegalPage.as_view(), name="legal"),
    path("contact", ContactFormView.as_view(), name="contact"),
    path("popular", PopularPage.as_view(), name="popular"),
    path("", HomePage.as_view(), name="home"),
]

src/profiles/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from .views import (
    hx_del_user_post,
    hx_img_post,
    hx_personal_data_post,
    public_profile,
    tab_account_data,
    tab_personal_data,
)

app_name = "profiles"
urlpatterns: list[URLPattern] = [
    path(
        route="u/<slug:username>",
        view=public_profile,
        name="detail",
    ),
    path(
        route="settings/personal_data/post",
        view=hx_personal_data_post,
        name="hx_personal_data_post",
    ),
    path(
        route="settings/image/post",
        view=hx_img_post,
        name="hx_img_post",
    ),
    path(
        route="settings/security/user/delete/post",
        view=hx_del_user_post,
        name="hx_del_user_post",
    ),
    path(
        route="settings/account_data",
        view=tab_account_data,
        name="settings_account_data",
    ),
    path(
        route="",
        view=tab_personal_data,
        name="settings",
    ),
]

src/profiles/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import PermissionDenied
from django.db import models
from django.shortcuts import get_object_or_404
from django.templatetags.static import static
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django_extensions.db.models import TimeStampedModel

from .utils import select_storage, set_base_img_url


class User(AbstractUser):
    def get_absolute_url(self):
        return reverse("profiles:detail", kwargs={"username": self.username})

    def get_social_url(self) -> str | None:
        socials = self.socialaccount_set  # type: ignore ; see django-allauth
        if socials.count():  # type: ignore ; see django-allauth
            if url := socials.first().get_avatar_url():
                return set_base_img_url(url)
        return None


class Profile(TimeStampedModel):
    """Creates some common properties:

    @property | description
    --:|:--
    `image_url` | The saved image related to the profile; if a `social_url` exists on signup, this is automatically used to create the `image_url`.
    `im_key` | Prevent duplicate names saved on file storage by establishing a convention for storing image files on each Profile

    """  # noqa: E501

    SuffixChoices = [
        ("Jr.", "Jr."),
        ("Sr.", "Sr."),
        ("III", "III"),
        ("IV", "IV"),
        ("V", "V"),
        ("VI", "VI"),
    ]
    GenderChoices = [("Male", "Male"), ("Female", "Female")]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)
    image = models.ImageField(storage=select_storage, blank=True, null=True)
    first_name = models.CharField(max_length=250, blank=True, null=True)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=250, blank=True, null=True)
    suffix = models.CharField(
        max_length=3, choices=SuffixChoices, blank=True, null=True
    )
    gender = models.CharField(
        max_length=7, choices=GenderChoices, blank=True, null=True
    )
    date_of_birth = models.DateField(_("Date of Birth"), blank=True, null=True)
    full_name = models.CharField(max_length=250)

    class Meta:
        db_table = "profiles"
        verbose_name = "User Profile"
        verbose_name_plural = "User Profiles"

    def __str__(self):
        if self.user.first_name != "" and self.user.last_name != "":
            fields = (self.first_name, self.last_name, self.suffix)
            return " ".join(f for f in fields if f)
        return str(self.user.username)

    def save(self, *args, **kwargs):
        self.full_name = str(self)
        super().save()  # Call the real save() method

    @classmethod
    def get_for_user(cls, profile_id: int, user: User):
        """Simple permission checking"""
        profile = get_object_or_404(cls, id=profile_id)
        if profile.user != user:
            raise PermissionDenied()
        return profile

    @cached_property
    def im_key(self):
        """Identifying key for image to store."""
        return f"profiles/{self.user.username}"

    @property
    def image_url(self) -> str:
        """URL to stored image object of user profile (or default)."""
        if self.image:
            if self.image.name.startswith("https://"):
                return self.image.name
            elif self.image.storage.exists(self.image.name):
                return self.image.storage.url(self.image.name)
        return static("img/smiler.png")

src/profiles/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.utils.translation import gettext_lazy as _

from .models import Profile, User


class ConsentBasicForm(SignupForm):
    user_consent = forms.BooleanField(required=True)


class ConsentSocialForm(SocialSignupForm):
    user_consent = forms.BooleanField(required=True)


class EditPersonalData(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            "first_name",
            "middle_name",
            "last_name",
            "suffix",
            "gender",
            "date_of_birth",
            "bio",
        )
        exclude = ("user",)
        labels = {"bio": _("About")}
        widgets = {
            "bio": forms.Textarea(attrs={"cols": 80, "rows": 4}),
            "date_of_birth": forms.DateInput(
                attrs={"type": "date", "placeholder": "mm/dd/yyyy (DOB)"}
            ),
        }


class EditProfileImage(forms.ModelForm):
    ALLOWED_TYPES = ["jpg", "jpeg", "png", "gif", "avif", "webp"]

    class Meta:
        model = Profile
        fields = ("image",)
        labels = {"image": _("Profile Image")}

    def clean_image(self):
        im = self.cleaned_data.get("image", None)

        if not im:
            raise forms.ValidationError("Missing image file")

        if not im.name.endswith(("jpg", "jpeg", "png", "avif", "web")):
            raise forms.ValidationError("Invalid file name extension.")

        if im.size > 2 * 1024 * 1024:
            raise forms.ValidationError("File too big, limit 2mb")

        return im


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("email", "username", "first_name", "last_name")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("email", "username", "first_name", "last_name")

src/profiles/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http.request import HttpRequest
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.template.response import TemplateResponse
from django.urls import reverse
from django.views.decorators.http import require_POST

from .forms import EditPersonalData, EditProfileImage
from .models import Profile
from .tasks import background_store_img_form


def public_profile(req: HttpRequest, username: str) -> TemplateResponse:
    return TemplateResponse(
        req,
        "profiles/detail.html",
        {"profile": get_object_or_404(Profile, user__username=username)},
    )


@login_required
def tab_personal_data(req: HttpRequest) -> TemplateResponse:
    return TemplateResponse(
        req,
        "profiles/tab_personal.html",
        {"form": EditPersonalData(instance=req.user.profile)},  # type: ignore
    )


@login_required
def tab_account_data(req: HttpRequest) -> TemplateResponse:
    return TemplateResponse(
        req, "profiles/tab_account.html", {"img_form": EditProfileImage}
    )


@login_required
@require_POST
def hx_personal_data_post(req: HttpRequest) -> TemplateResponse:
    form = EditPersonalData(data=req.POST, instance=req.user.profile)  # type: ignore
    if form.is_valid():
        form.save()
        messages.add_message(req, messages.SUCCESS, "General fields updated!")
    return TemplateResponse(req, "profiles/tab_personal.html", {"form": form})


@login_required
@require_POST
def hx_img_post(req: HttpRequest) -> HttpResponseRedirect:
    if upload := req.FILES.get("id_image"):
        form = EditProfileImage(req.POST, req.FILES, instance=req.user.profile)  # type: ignore # noqa: E501
        if form.is_valid():
            background_store_img_form(upload, form.instance.image, form.instance.im_key)
            messages.add_message(
                req,
                messages.SUCCESS,
                "Image being processed! Should be available soon.",
            )
        else:
            if err_msg := form.errors.get("image"):
                for msg in err_msg:
                    messages.add_message(req, messages.ERROR, msg)
    return HttpResponseRedirect(reverse("profiles:settings_account_data"))


@login_required
@require_POST
def hx_del_user_post(req: HttpRequest) -> HttpResponseRedirect:
    if req.user.is_active:
        req.user.delete()  # TODO: how to show message on redirect
    return HttpResponseRedirect(reverse("pages:home"))

src/templates/profiles/tabs/_tab_account_proper.html
{% include 'text/action_panel.html' with heading="Change photo" caption="Upload / change a profile image." cta="profiles/tabs/tab_account/_edit_image_form.html" %}
{% include 'text/action_panel.html' with heading="Delete account" caption="This cannot be reversed." cta="profiles/tabs/tab_account/_delete_profile_button.html" %}

src/templates/profiles/tabs/_tab_personal_proper.html
{% load static start fragments %}
<div class="px-4">
  <form>
    <div class="flex-grow space-y-6">
      <div class="grid grid-cols-12 gap-6 mt-6">
        {% hput form.first_name kls="fx col-span-12 sm:col-span-3" %}
        {% hput form.middle_name kls="fx col-span-12 sm:col-span-3" %}
        {% hput form.last_name kls="fx col-span-12 sm:col-span-3" %}
        {% sel form.suffix idx="sfx-id" kls="col-span-12 sm:col-span-3" %}
        {% sel form.gender idx="gender-id" kls="col-span-12 sm:col-span-6" %}
        {% hput form.date_of_birth kls="fx col-span-12 sm:col-span-6" %}
      </div>
      {% hput form.bio kls='fx' %}
    </div>
    {% url 'profiles:hx_personal_data_post' as target_hx_url %}
    <div class="flex gap-x-3 justify-start py-4 mt-4">
      <button data-btn="primary" class="w-full btn" hx-post="{{target_hx_url}}" hx-swap="none">Updated</button>
    </div>{# although hx-swap is operative, hx-oob will still be respected; relate to alert in parent template #}
  </form>
</div>

src/templates/profiles/tabs/tab_settings.html
{% load static account start fragments %}
{% if request.user.is_active %}{# this layout is for tabbed user settings #}
  <div class="px-4 pb-6 mx-auto max-w-screen-xl sm:px-6 lg:px-8 lg:pb-16">
    <div class="overflow-hidden rounded-lg shadow dark:shadow-sm dark:shadow-slate-700">
      <div class="lg:grid lg:grid-cols-12">
        <aside class="py-6 lg:col-span-3">
          <div class="hidden overflow-hidden relative mx-6 lg:block">
            <div class="mb-2 sm:mb-4">
              <img class="relative rounded-md object-fit aspect-square w-100" src="{{request.user.profile.image_url}}" alt="{{request.user.profile|default:'Default image.'}}">
            </div>
          </div>
          <nav class="flex flex-col mx-6 space-y-1 sm:mt-6 m:mx-8" aria-label="user-setting-tabs">
            <a {% curr request.path 'profiles:settings' %} href="{% url 'profiles:settings' %}" class="flex items-center py-2 px-3 text-sm font-medium rounded-md focus:ring-1 focus:outline-none text-grayed-muted aria-current:text-dawn-darkerdark:text-grayed-muted dark:hover:text-fuchsia-200 dark:focus:ring-grayed-darker dark:aria-current:text-fuchsia-400 hover:text-dawn-muted focus:ring-grayed-lighter" tabindex="0">
              {% icon name='user_circle' css="-ml-1 mr-3 h-6 w-6 flex-shrink-0 text-dawn-darker dark:text-dusk-lighter" post_text="Personal Data" post_class="truncate" %}
            </a>

            <a {% curr request.path 'account_email' %} href="{% url 'account_email' %}" class="flex items-center py-2 px-3 text-sm font-medium rounded-md focus:ring-1 focus:outline-none text-grayed-muted aria-current:text-dawn-darkerdark:text-grayed-muted dark:hover:text-fuchsia-200 dark:focus:ring-grayed-darker dark:aria-current:text-fuchsia-400 hover:text-dawn-muted focus:ring-grayed-lighter" tabindex="0">
              {% icon name='at_symbol' css="-ml-1 mr-3 h-6 w-6 flex-shrink-0 text-dawn-darker dark:text-dusk-lighter" post_text="Email" post_class="truncate" %}
            </a>

            {% if password_set_form %}{# form in context in a password_change_url = django-allauth switch for password management #}
              <a {% curr request.path 'account_set_password' %} href="{% url 'account_change_password' %}" class="flex items-center py-2 px-3 text-sm font-medium rounded-md focus:ring-1 focus:outline-none text-grayed-muted aria-current:text-dawn-darkerdark:text-grayed-muted dark:hover:text-fuchsia-200 dark:focus:ring-grayed-darker dark:aria-current:text-fuchsia-400 hover:text-dawn-muted focus:ring-grayed-lighter" tabindex="0">
                {% icon name='key' css="-ml-1 mr-3 h-6 w-6 flex-shrink-0 text-dawn-darker dark:text-dusk-lighter" post_text="Password" post_class="truncate" %}
              </a>
            {% else %}
              <a {% curr request.path 'account_change_password' %} href="{% url 'account_change_password' %}" class="flex items-center py-2 px-3 text-sm font-medium rounded-md focus:ring-1 focus:outline-none text-grayed-muted aria-current:text-dawn-darkerdark:text-grayed-muted dark:hover:text-fuchsia-200 dark:focus:ring-grayed-darker dark:aria-current:text-fuchsia-400 hover:text-dawn-muted focus:ring-grayed-lighter" tabindex="0">
                {% icon name='key' css="-ml-1 mr-3 h-6 w-6 flex-shrink-0 text-dawn-darker dark:text-dusk-lighter" post_text="Password" post_class="truncate" %}
              </a>
            {% endif %}

            <a {% curr request.path 'socialaccount_connections' %} href="{% url 'socialaccount_connections' %}" class="flex items-center py-2 px-3 text-sm font-medium rounded-md focus:ring-1 focus:outline-none text-grayed-muted aria-current:text-dawn-darkerdark:text-grayed-muted dark:hover:text-fuchsia-200 dark:focus:ring-grayed-darker dark:aria-current:text-fuchsia-400 hover:text-dawn-muted focus:ring-grayed-lighter" tabindex="0">
              {% icon name='user_plus' css="-ml-1 mr-3 h-6 w-6 flex-shrink-0 text-dawn-darker dark:text-dusk-lighter" post_text="Social Login" post_class="truncate" %}
            </a>

            <a {% curr request.path 'profiles:settings_account_data' %}  href="{% url 'profiles:settings_account_data' %}" class="flex items-center py-2 px-3 text-sm font-medium rounded-md focus:ring-1 focus:outline-none text-grayed-muted aria-current:text-dawn-darkerdark:text-grayed-muted dark:hover:text-fuchsia-200 dark:focus:ring-grayed-darker dark:aria-current:text-fuchsia-400 hover:text-dawn-muted focus:ring-grayed-lighter" tabindex="0">
              {% icon name='adjustments_horizontal' css="-ml-1 mr-3 h-6 w-6 flex-shrink-0 text-dawn-darker dark:text-dusk-lighter" post_text="Account Settings" post_class="truncate" %}
            </a>
          </nav>
        </aside>
        <div class="px-4 sm:px-6 lg:col-span-9">
          <div class="py-6 px-4 sm:p-6 lg:pb-8">
            {% include 'text/header.html' with heading=heading caption=caption heading_css="text-3xl text-dawn-darker/90 dark:text-fuchsia-400/90" %}
            {% if tab_panel_template %}
              <div class="mt-6">
                {% include tab_panel_template %}
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% endif %}